import { it } from 'vitest';
import { capitalSummary } from '@/intelligence/capital';
import { computeItemIntel, todayPriorities } from '@/intelligence/decision';
import { favoriteGains } from '@/intelligence/favorites';
import { summarizeLearning } from '@/intelligence/learning';
import { DEFAULT_MARKDOWN, startPrices } from '@/intelligence/markdown';
import { latestAnalyses } from '@/intelligence/market-vs-you';
import { buildItemViews, buildSaleViews } from '@/intelligence/portfolio';
import { precisionRows } from '@/intelligence/precision';
import { refundSummary } from '@/intelligence/refunds';
import { lastReposts } from '@/intelligence/repost';
import { buildSellerModel } from '@/intelligence/seller-model';
import { buildSensitivityIndex, lastDrops } from '@/intelligence/sensitivity';
import { workshopQueue } from '@/intelligence/workshop';
import { bigInputs } from './fixture';
import { time } from './timing';

it('where the dashboard time goes', () => {
  const x = bigInputs();
  const now = x.now;
  const obs = x.observations!;
  const pe = x.priceEvents!;
  const views = buildItemViews(x.items!, x.listings!, x.sales!, now);
  const sv = buildSaleViews(views, x.sales!);
  const model = buildSellerModel(views, sv, { category: (c) => c });
  const learning = summarizeLearning(x.predictions!);
  const capital = capitalSummary(views, sv, now, model.medianDays);
  const am = new Map(x.analyses!.map((a) => [a.inventoryItemId!, a.analysis]));
  const sens = buildSensitivityIndex(views, obs, pe);
  const drops = lastDrops(pe, obs, now);
  const reposts = lastReposts(x.repostEvents!, obs, now);
  const intel = views.filter((v) => v.inStock).map((v) => computeItemIntel(v, am.get(v.item.id) ?? null, model, learning, capital, now, sens.get(v.item.id), drops.get(v.item.id) ?? null, reposts.get(v.item.id) ?? null));
  void DEFAULT_MARKDOWN;
  time('buildItemViews', () => buildItemViews(x.items!, x.listings!, x.sales!, now));
  time('buildSaleViews', () => buildSaleViews(views, x.sales!));
  time('buildSellerModel', () => buildSellerModel(views, sv, { category: (c) => c }));
  time('summarizeLearning', () => summarizeLearning(x.predictions!));
  time('capitalSummary', () => capitalSummary(views, sv, now, model.medianDays));
  time('buildSensitivityIndex', () => buildSensitivityIndex(views, obs, pe));
  time('lastDrops', () => lastDrops(pe, obs, now));
  time('lastReposts', () => lastReposts(x.repostEvents!, obs, now));
  time('computeItemIntel × stock', () => views.filter((v) => v.inStock).map((v) => computeItemIntel(v, am.get(v.item.id) ?? null, model, learning, capital, now, sens.get(v.item.id), drops.get(v.item.id) ?? null, reposts.get(v.item.id) ?? null)));
  time('workshopQueue', () => workshopQueue(views, new Map()));
  time('refundSummary', () => refundSummary(sv, { category: (c) => c }));
  time('todayPriorities', () => todayPriorities(intel, capital, model, views));
  time('favoriteGains', () => favoriteGains(views, obs, now));
  time('startPrices (one pass)', () => startPrices(obs, pe));
  time('latestAnalyses', () => latestAnalyses(x.analyses!));
  time('precisionRows', () => precisionRows(x.predictions!));
});
